# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e7cdf8200bfe492c5c5de08ce596c2e1c155ddadfb2a13db023d0c625936fe59f4f7ec9266d427634343ab7bbe022517a4be3f9090d5775777808e662d35c7d5

test:
  secret_key_base: 741f3753d2b11bd7ab4b85dad4e5d12bb66fe09488f1719ed8b4e7754d92368c306e9b19e864f29d57e788a578d8bcbe3f80e7f124b6f0d3d184185595606530

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
